export default { 	id: '17327',
					name: 'Greig Laidlaw',
					dob: '12/10/1985',
					heightm: '1.76 m',
					weightm: '80 kg',
					heighti: '5\' 9"',
					weighti: '12 st 8 lb',
					birthplace: 'Edinburgh, Scotland',
					birthcountry: '',
					position: 'Coach',
					honours: 'Scotland (58 caps)',
					image: 'https://cdn.soticservers.net/tools/images/players/photos/2016/lions/127/250x250/17327.jpg',
					thumb: 'https://cdn.soticservers.net/tools/images/teams/logos/70x70-ffffff/127.gif',
					optaid: '8420',
					club: 'Gloucester Rugby',
					start: 52,
					used: 64,
					sub: 12,
					try: 2,
					conv: 100,
					drop: 0,
					pen: 147,
					yell: 2,
					red: 0,
					points: 651,
					logo: 'https://cdn.soticservers.net/tools/images/teams/logos/250x250/127.png',
					country: 'SCOTLAND',
					countryid: '127',
					education: 'Hamilton Boys\' High School and Waitako University',
					biog:"<h1>Playing Career</h1><p>At the Official Shop, you can take your pick from our full range of clothing or accessories to accompany your wardrobe, including the iconic British & Irish Lions jersey.</p><h1>Coaching Career</h1><p>We also have a range of classic jerseys, t-shirts, gifts, leisure-wear and more. No matter what kind of rugby fan you are, the Official Lions Shop has something to help you show your support for the 2017 squad.</p><h1>Ireland</h1><p>Ordering with the Official Shop couldn’t be easier, with fast delivery options available to most locations across the globe, and hassle free returns to ensure </p>"
				}