export default [{   year:2017,
                    month:1,
                    day:7,
                    hour:7,
                    minute:0,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:1,
                    day:14,
                    hour:7,
                    minute:0,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:1,
                    day:28,
                    hour:7,
                    minute:0,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:2,
                    day:14,
                    hour:7,
                    minute:0,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:2,
                    day:21,
                    hour:7,
                    minute:0,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:3,
                    day:4,
                    hour:7,
                    minute:0,
                    second:0,
                    message:"Only acouple of weeks until the official Lions squad is announced, log into My Lions to finalise your squad"
                }]
