export default [{   year:2017,
                    month:1,
                    day:7,
                    hour:9,
                    minute:30,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
{   year:2017,
  month:1,
  day:7,
  hour:23,
  minute:30,
  second:0,
  message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
},
  {   year:2017,
    month:1,
    day:7,
    hour:0,
    minute:30,
    second:0,
    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
  },{   year:2017,
    month:1,
    day:7,
    hour:1,
    minute:30,
    second:0,
    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
  },{   year:2017,
    month:1,
    day:7,
    hour:2,
    minute:30,
    second:0,
    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
  },{   year:2017,
    month:1,
    day:7,
    hour:3,
    minute:30,
    second:0,
    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
  },{   year:2017,
    month:1,
    day:7,
    hour:4,
    minute:30,
    second:0,
    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
  },{   year:2017,
    month:1,
    day:7,
    hour:5,
    minute:30,
    second:0,
    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
  },{   year:2017,
    month:1,
    day:7,
    hour:6,
    minute:30,
    second:0,
    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
  },{   year:2017,
    month:1,
    day:7,
    hour:7,
    minute:30,
    second:0,
    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
  },{   year:2017,
    month:1,
    day:7,
    hour:8,
    minute:30,
    second:0,
    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
  },{   year:2017,
    month:1,
    day:7,
    hour:9,
    minute:30,
    second:0,
    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
  },{   year:2017,
    month:1,
    day:7,
    hour:10,
    minute:30,
    second:0,
    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
  },{   year:2017,
    month:1,
    day:7,
    hour:11,
    minute:30,
    second:0,
    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
  },
                {   year:2017,
                    month:1,
                    day:14,
                    hour:9,
                    minute:30,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:1,
                    day:28,
                    hour:9,
                    minute:30,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:2,
                    day:14,
                    hour:9,
                    minute:30,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:2,
                    day:21,
                    hour:9,
                    minute:30,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:3,
                    day:4,
                    hour:9,
                    minute:30,
                    second:0,
                    message:"Only acouple of weeks until the official Lions squad is announced, log into My Lions to finalise your squad"
                },
                {
                    year:2017,
                    month:0,
                    day:31,
                    hour:8,
                    minute:20,
                    second:0,
                    message:"This is for testing purposes."
                },{
                      year:2017,
                      month:0,
                      day:31,
                      hour:9,
                      minute:0,
                      second:0,
                      message:"This is for testing purpose only and will be removed after released."
                 }]
