export default [{   year:2017,
                    month:1,
                    day:7,
                    hour:9,
                    minute:30,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:1,
                    day:14,
                    hour:9,
                    minute:30,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:1,
                    day:28,
                    hour:9,
                    minute:30,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:2,
                    day:14,
                    hour:9,
                    minute:30,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:2,
                    day:21,
                    hour:9,
                    minute:30,
                    second:0,
                    message:"Player statistics have been updated from the weekend's games, log into My Lions to update your squad"
                },
                {   year:2017,
                    month:3,
                    day:4,
                    hour:9,
                    minute:30,
                    second:0,
                    message:"Only acouple of weeks until the official Lions squad is announced, log into My Lions to finalise your squad"
                },
                {
                    year:2017,
                    month:0,
                    day:31,
                    hour:8,
                    minute:20,
                    second:0,
                    message:"This is for testing purposes."
                },{
                      year:2017,
                      month:0,
                      day:31,
                      hour:9,
                      minute:0,
                      second:0,
                      message:"This is for testing purpose only and will be removed after released."
                 }]
